theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

hero:
  # background: "/assets/images/hero.jpg"

author:
  name: "Your Name"
  avatar: "/assets/images/bio-photo.jpg"
  bio: "Assistant Professor of Finance, University of Michigan"

# Navigation menu
navigation:
  main:
    - title: "Home"
      url: /
    - title: "CV"
      url: /cv/
    - title: "Research"
      url: /Research/
    - title: "Policy"
      url: /Policy/
    # - title: "Contact"
    #   url: /contact/